create table public.riwayat_assesment (
  id uuid not null default gen_random_uuid (),
  employee_id uuid not null default gen_random_uuid (),
  remarks text null,
  age smallint null,
  code_subho character varying null,
  code_subco character varying null,
  integ_int character varying null,
  exc_int character varying null,
  hum_int character varying null,
  value_driven character varying null,
  adm_int character varying null,
  plc_int character varying null,
  mch_int character varying null,
  ftw_int character varying null,
  emp_int character varying null,
  leadership_comp character varying null,
  people character varying null,
  organization character varying null,
  business character varying null,
  business_comp character varying null,
  persistent character varying null,
  perseverance character varying null,
  passion character varying null,
  grit character varying null,
  technical_comp character varying null,
  overal_score character varying null,
  talent_class character varying null,
  strength character varying null,
  area_of_dev character varying null,
  idp character varying null,
  iq character varying null,
  disc character varying null,
  comp_int text null,
  assesment_year smallint not null,
  hav text null,
  hav_tia text null,
  constraint riwayat_assesment_pkey primary key (id),
  constraint uniq_assesment_employee_year unique (employee_id, assesment_year),
  constraint riwayat_assesment_employee_id_fkey foreign KEY (employee_id) references employees (employee_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;